"""Create column observations in Orders

Revision ID: 11436336415a
Revises: 2ea0c4d22718
Create Date: 2025-05-30 11:34:57.774133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11436336415a'
down_revision: Union[str, None] = '2ea0c4d22718'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('orders', sa.Column('observations', sa.String(length=500), nullable=True))
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=50), nullable=False))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.alter_column('refresh_tokens', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('product_images', 'public_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('orders', 'observations')
    # ### end Alembic commands ###
