"""test

Revision ID: 15185dd16119
Revises: 11436336415a
Create Date: 2025-05-30 19:57:06.838477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15185dd16119'
down_revision: Union[str, None] = '11436336415a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('product_images', 'public_id',
            #    existing_type=sa.VARCHAR(),
            #    nullable=False)
    # op.alter_column('refresh_tokens', 'is_active',
    #            existing_type=sa.BOOLEAN(),
    #            nullable=False)
    # op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    # op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=50), nullable=False))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.alter_column('refresh_tokens', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('product_images', 'public_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
