"""add images table

Revision ID: 296ac5626a68
Revises: c81211b3e10b
Create Date: 2025-05-25 19:31:25.848505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '296ac5626a68'
down_revision: Union[str, None] = 'c81211b3e10b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('customers', sa.Column('notes', sa.String(length=255), nullable=True))
    # op.drop_column('customers', 'observations')
    # op.add_column('product_images', sa.Column('is_main', sa.Boolean(), nullable=False))
    # op.alter_column('refresh_tokens', 'is_active',
    #            existing_type=sa.BOOLEAN(),
    #            nullable=False)
    # op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    # op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=50), nullable=False))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.alter_column('refresh_tokens', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('product_images', 'is_main')
    op.add_column('customers', sa.Column('observations', sa.VARCHAR(length=255), nullable=True))
    op.drop_column('customers', 'notes')
    # ### end Alembic commands ###
