"""Change sinced_with_cianbox column to new table id

Revision ID: 2ea0c4d22718
Revises: 5e7ed5e190e1
Create Date: 2025-05-30 09:43:15.962067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ea0c4d22718'
down_revision: Union[str, None] = '5e7ed5e190e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('orders', 'synced_with_cianbox')
    # op.alter_column('product_images', 'public_id',
    #            existing_type=sa.VARCHAR(),
    #            nullable=False)
    # op.alter_column('refresh_tokens', 'is_active',
    #            existing_type=sa.BOOLEAN(),
    #            nullable=False)
    # op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    # op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=50), nullable=False))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.alter_column('refresh_tokens', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('product_images', 'public_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('orders', sa.Column('synced_with_cianbox', sa.BOOLEAN(), nullable=False))
    # ### end Alembic commands ###
