"""Delete table Roles

Revision ID: 4e72163045c0
Revises: 703b1cd60059
Create Date: 2025-06-01 10:38:41.210419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e72163045c0'
down_revision: Union[str, None] = '703b1cd60059'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index('ix_roles_id', table_name='roles')
    # op.drop_table('roles')
    # op.alter_column('product_images', 'public_id',
    #            existing_type=sa.VARCHAR(),
    #            nullable=False)
    # op.alter_column('refresh_tokens', 'is_active',
    #            existing_type=sa.BOOLEAN(),
    #            nullable=False)
    # op.add_column('users', sa.Column('role', sa.String(length=50), nullable=False, server_default='customer'))
    # op.drop_constraint(None, 'users', type_='foreignkey')
    # op.drop_column('users', 'role_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role_id', sa.INTEGER(), nullable=False))
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    op.drop_column('users', 'role')
    op.alter_column('refresh_tokens', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('product_images', 'public_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_table('roles',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_roles_id', 'roles', ['id'], unique=False)
    # ### end Alembic commands ###
