"""Add public_id column to ProductImages

Revision ID: 5e7ed5e190e1
Revises: d9dcc6d317e0
Create Date: 2025-05-29 09:20:57.853995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e7ed5e190e1'
down_revision: Union[str, None] = 'd9dcc6d317e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('product_images', sa.Column('public_id', sa.String()))
    # op.alter_column('refresh_tokens', 'is_active',
    #            existing_type=sa.BOOLEAN(),
    #            nullable=False)
    # op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    # op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=50), nullable=False))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.alter_column('refresh_tokens', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('product_images', 'public_id')
    # ### end Alembic commands ###
