"""create table users again

Revision ID: 703b1cd60059
Revises: 15185dd16119
Create Date: 2025-05-30 20:02:17.300771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '703b1cd60059'
down_revision: Union[str, None] = '15185dd16119'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('product_images', 'public_id',
    #            existing_type=sa.VARCHAR(),
    #            nullable=False)
    # op.alter_column('refresh_tokens', 'is_active',
    #            existing_type=sa.BOOLEAN(),
    #            nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('refresh_tokens', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('product_images', 'public_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
