"""Replace is_main column with position

Revision ID: d9dcc6d317e0
Revises: 296ac5626a68
Create Date: 2025-05-26 15:50:05.970489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9dcc6d317e0'
down_revision: Union[str, None] = '296ac5626a68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('product_images', sa.Column('position', sa.Integer(), nullable=False))
    # op.add_column('product_images', sa.Column('created_at', sa.DateTime(), nullable=False))
    # op.drop_column('product_images', 'is_main')
    # op.alter_column('refresh_tokens', 'is_active',
    #            existing_type=sa.BOOLEAN(),
    #            nullable=False)
    # op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    # op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=50), nullable=False))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.alter_column('refresh_tokens', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.add_column('product_images', sa.Column('is_main', sa.BOOLEAN(), nullable=False))
    op.drop_column('product_images', 'created_at')
    op.drop_column('product_images', 'position')
    # ### end Alembic commands ###
